🧑‍💻 ci: print cache ownership check in Renovate workflow

diff --git a/.gitea/workflows/renovate.yml b/.gitea/workflows/renovate.yml
--- a/.gitea/workflows/renovate.yml
+++ b/.gitea/workflows/renovate.yml
@@ -28,8 +28,12 @@ jobs:
       - name: Fix restore Renovate cache ownership
         if: steps.cache-repos.outputs.cache-matched-key != ''
         run: |
-          sudo chown -R 12021:0 /tmp/renovate/
-          ls -R "$cache_dir"
+          if [ -d "/tmp/renovate/" ]; then
+            echo "Fixing ownership: /tmp/renovate/"
+            sudo chown -R 12021:0 /tmp/renovate/
+          fi
+
+          ls -R "$cache_repos_dir" || echo "Renovate repositories cache directory not found: $cache_repos_dir"
 
       - name: Run self-hosted Renovate
         uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
