ci: update merge Renovate host rules and change workflow weekdays schedule (#41)
## Summary
- Renovate host rules 설정 과정을 step 한 개로 통합.
- 환경 변수 이름을 대문자로 변경.
- workflow가 평일에 실행되는 시간 변경. 평일에는 1시간마다 실행되지 않고 2~3시간 정도로 실행되도록 시간 조정.

diff --git a/.gitea/workflows/renovate.yml b/.gitea/workflows/renovate.yml
--- a/.gitea/workflows/renovate.yml
+++ b/.gitea/workflows/renovate.yml
@@ -2,8 +2,12 @@ name: Self-hosted Renovate
 
 on:
   schedule:
-    - cron: '21 * * * 1-5'
+    # Weekdays
+    - cron: '21 0-6/3,8 * * 1-5'
+    - cron: '21 11-13/2,22 * * 1-5'
+    # Weekends
     - cron: '21 6,14,23 * * 0,6'
+
   workflow_dispatch:
     inputs:
       dry-run:
@@ -29,8 +33,8 @@ on:
         type: number
 
 env:
-  cache_repos_dir: /tmp/renovate/cache/renovate/repository
-  cache_repos_key: renovate-repos-cache
+  CACHE_REPOS_DIR: /tmp/renovate/cache/renovate/repository
+  CACHE_REPOS_KEY: renovate-repos-cache
 
 permissions: {}
 
@@ -44,11 +48,11 @@ jobs:
         uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
         id: cache-repos
         with:
-          path: ${{ env.cache_repos_dir }}
-          key: ${{ env.cache_repos_key }}.${{ gitea.run_id }}-${{ gitea.run_attempt }}
+          path: ${{ env.CACHE_REPOS_DIR }}
+          key: ${{ env.CACHE_REPOS_KEY }}.${{ gitea.run_id }}-${{ gitea.run_attempt }}
           restore_keys: |
-            ${{ env.cache_repos_key }}.${{ gitea.run_id }}-
-            ${{ env.cache_repos_key }}.
+            ${{ env.CACHE_REPOS_KEY }}.${{ gitea.run_id }}-
+            ${{ env.CACHE_REPOS_KEY }}.
 
       - name: Fix restore Renovate cache ownership
         if: steps.cache-repos.outputs.cache-matched-key != ''
@@ -58,27 +62,25 @@ jobs:
             sudo chown -R 12021:0 /tmp/renovate/
           fi
 
-          ls -R "$cache_repos_dir" || echo "Renovate repositories cache directory not found: $cache_repos_dir"
+          ls -R "$CACHE_REPOS_DIR" || echo "Renovate repositories cache directory not found: $CACHE_REPOS_DIR"
 
-      - name: Setup Renovate host rule - docker.io
-        id: host-rule-docker-io
-        if: secrets.RENO_DOCKERHUB_USERNAME != '' && secrets.RENO_DOCKERHUB_PASSWORD != ''
+      - name: Setup Renovate host rules
+        id: renovate-host-rules
         env:
           DOCKERHUB_USERNAME: ${{ secrets.RENO_DOCKERHUB_USERNAME }}
           DOCKERHUB_PASSWORD: ${{ secrets.RENO_DOCKERHUB_PASSWORD }}
         run: |
-          host_rule=$(echo '{"hostType":"docker","matchHost":"docker.io"}' | jq -rc --arg username "$DOCKERHUB_USERNAME" --arg password "$DOCKERHUB_PASSWORD" '. += { "username": $username, "password": $password }')
-          echo "host-rule=$host_rule" >> $GITEA_OUTPUT
-
-      - name: Setup Renovate merge host rules
-        id: renovate-host-rules
-        env:
-          HOST_RULE_DOCKER_IO: ${{ steps.host-rule-docker-io.outputs.host-rule }}
-        run: |
           host_rules='[]'
 
-          if [ -n "$HOST_RULE_DOCKER_IO" ]; then
-            host_rules=$(echo "$host_rules" | jq -rc ". += [$HOST_RULE_DOCKER_IO]")
+          if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_PASSWORD" ]; then
+            echo "Setup host rule - docker.io"
+
+            host_rules=$(echo "$host_rules" | jq -rc \
+              --arg username "$DOCKERHUB_USERNAME" --arg password "$DOCKERHUB_PASSWORD" \
+              '. += [{ "hostType": "docker", "matchHost": "docker.io", $username, $password }]'
+            )
+          else
+            echo "Skip setup host rule  - docker.io"
           fi
 
           total_count=$(echo "$host_rules" | jq -r '. | length')
